print("\033[1;32;40m")# Renkli yazmak için
print("╔══════════════════════╗")
print("║     Proje Listesi    ║")
print("║  1.Hesap Makinesi    ║")
print("║  2.Tahmin Oyunu      ║")
print("║  3.Vki Hesaplama     ║")
print("║  4.Kur Dönüstürücü   ║")
print("║  5.Puan Hesaplama    ║")
print("║  6.Ruh Halini Söyle  ║")
print("║  7.Geometrik Şekiller║")
print("║                      ║")
print("║ Seciminiz nedir?     ║")
print("╚══════════════════════╝")
ana_menü2()